version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 99
  target-branch: main
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.26.0
    - 8.28.0
    - 8.30.0
    - 8.30.1
    - 8.32.0
    - 8.33.0
    - 8.35.0
    - 8.36.0
    - 8.36.1
    - 8.39.0
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 99
  target-branch: main
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.11
    - 8.2.5
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: laravel-mix
    versions:
    - 6.0.12
    - 6.0.15
