version: "3"
services:
  nexus:
    build:
      context: .
    ports:
      - 4000:80
    volumes:
      - "..:/app/nexus"
    depends_on:
      - mysql
  pma:
    image: "phpmyadmin"
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "nexus"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "nexus_dev_db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

volumes:
  nexus_dev_db:
