name: Test

on:
  push:
    branches:
      - "*"
      - "**"
    tags-ignore:
      - v*
  pull_request:

jobs:
  test:
    name: PHP
    runs-on: ubuntu-latest
    concurrency:
      group: nexus-test-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        php: ["8.4"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #
      # ENVIRONMENT DEPENDENCIES SETUP
      #
      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Start MySQL and Create Databases
      - name: Create Databases
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE IF NOT EXISTS nexus;' -h127.0.0.1 -uroot -proot

      #
      # COMPOSER DEPENDENICES
      #

      # Add Github Auth to Composer
      - name: Add Composer GitHub Token
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ hashFiles('**/composer.lock') }}
            composer-

      # Install
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest

      #
      # NODE DEPENDENCIES
      #

      - name: Node Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            public/build
            public/css
            public/js
            public/mix-manifest.json
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('**/package-lock.json') }}
            npm-

      # Install
      - name: Install assets
        run: npm ci

      - name: Compile assets
        run: npm run build

      - name: Set Environment Variables
        uses: allenevans/set-env@v2.0.0
        with:
          APP_ENV: testing
          APP_KEY: base64:wx/g4ayECKlSzOYSguRFoCrsd+KSbAyEiy0J8zWxxyU=
          APP_URL: http://127.0.0.1
          CACHE_DRIVER: array
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_DATABASE: nexus

      # Run Database Migration
      - name: Migrate Database
        run: php artisan migrate

      # Cache Setup
      - name: Cache Routes
        run: php artisan route:cache

      - name: Clear Config Cache
        run: php artisan config:clear

      # Start Application
      - name: Serve Application
        run: php artisan serve -q &

      # Run Tests
      - name: Execute Tests
        run: php artisan test

  trigger-deploy:
    name: Trigger Deployment
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      #
      # DEPLOY (main only)
      #
      - name: Trigger Deploy workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: deploy-trigger
